name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VITE_SERVER_URL: ${{vars.VITE_SERVER_URL}}
      VITE_razorpayKeyId: ${{vars.VITE_razorpayKeyId}}
      VITE_GOOGLE_MAP_API_KEY: ${{vars.VITE_GOOGLE_MAP_API_KEY}}
      VITE_CompanyName: ${{vars.VITE_CompanyName}}
      VITE_omapnyDescription: ${{vars.VITE_omapnyDescription}}
      VITE_PUBLIC_GOOGLE_CLIENT_ID: ${{vars.VITE_PUBLIC_GOOGLE_CLIENT_ID}}

    steps:
    - name: Read a variable
      run: echo "My VITE_SERVER_URL value is ${{ vars.VITE_SERVER_URL }}"
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 91.108.110.252 >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        scp -o StrictHostKeyChecking=no -r ./dist/* root@91.108.110.252:/var/www/customer.bellybasketsotre.com/dist
